# file: roles/eclipse/tasks/main.yml
---

- name: Prepare Eclipse download script
  template: src=eclipse_download.j2
            dest={{ eclipse_localdir }}/eclipse_download.sh
            mode=0555

- name: Download Eclipse
  command: creates="{{ eclipse_localdir }}/{{ eclipse_archive }}"
           "{{ eclipse_localdir }}/eclipse_download.sh"

- name: Extract Eclipse
  command: chdir="{{ eclipse_localdir }}" creates="eclipse"
           tar -xvf "{{ eclipse_archive }}"

- name: Eclipse directory owner and group
  file: state=directory path="{{ eclipse_localdir }}/eclipse"
        recurse=yes owner="{{ eclipse_owner }}" group="{{ eclipse_owner }}"

- name: Eclipse configuration settings files
  with_subelements:
  - "{{ eclipse_configuration | default([]) }}"
  - prefs
  lineinfile: dest="{{ eclipse_localdir }}/eclipse/configuration/.settings/{{
                    item.0.module }}.prefs"
              line="{{ item.1.key }}={{ item.1.val }}"
              regexp="^\s*{{ item.1.key }}=.*$" state=present
              create=yes owner="{{ eclipse_owner }}" group="{{ eclipse_owner }}"

- name: Eclipse feature groups
  with_items: "{{ eclipse_feature_groups | default([]) }}"
  command: >
           {{ eclipse_localdir }}/eclipse/eclipse
           -clean -purgeHistory
           -application org.eclipse.equinox.p2.director -noSplash
           -repository {{ item.repository }}
           -destination "{{ eclipse_localdir }}/eclipse"
           -profileProperties org.eclipse.update.install.features=true
           -installIU {{ item.units | join(',') }}
  ignore_errors: yes
