---
# file: roles/eclipse/tasks/main.yml

- name: Prepare Eclipse download script
  template: src=eclipse_download.j2
            dest={{ eclipse_localdir }}/eclipse_download.sh
            mode=0555

- name: Download Eclipse
  command: creates="{{ eclipse_localdir }}/{{ eclipse_archive }}"
           "{{ eclipse_localdir }}/eclipse_download.sh"

- name: Extract Eclipse
  command: chdir="{{ eclipse_localdir }}" creates="eclipse"
           tar -xvf "{{ eclipse_archive }}"

- name: Eclipse directory owner and group
  file: state=directory path="{{ eclipse_localdir }}/eclipse"
        recurse=yes owner={{ eclipse_owner }} group={{ eclipse_owner }}

- name: Create Eclipse desktop launcher icon
  template: src=eclipse.desktop.j2
            dest=~{{ eclipse_owner }}/.local/share/applications/eclipse.desktop
            owner={{ eclipse_owner }} group={{ eclipse_owner }}

- set_fact: eclipse_release_repo="http://download.eclipse.org/releases/{{
                                  eclipse_release|mandatory|lower }}"

- name: Eclipse feature groups
  with_items:

  # Git
  - repository: "{{ eclipse_release_repo }}"
    units:
    - org.eclipse.egit.feature.group
    - org.eclipse.jgit.feature.group
    - org.eclipse.jgit.java7.feature.group
    - org.eclipse.jgit.pgm.feature.group

  # CDT (provides org.eclipse.cdt.managedbuilder.core.headlessbuild)
  - repository: "{{ eclipse_release_repo }}"
    units:
    - org.eclipse.cdt.feature.group

  - repository: "http://download.eclipse.org/webtools/repository/{{ eclipse_release|mandatory|lower }}"
    units:
    # Dali Java Persistence Tools
    - org.eclipse.jpt.common.feature.feature.group
    - org.eclipse.jpt.common.eclipselink.feature.feature.group
    - org.eclipse.jpt.jpa.eclipselink.feature.feature.group
    - org.eclipse.jpt.jaxb.eclipselink.feature.feature.group
    # JST Java Standard Tools
    - org.eclipse.jst.enterprise_ui.feature.feature.group
    - org.eclipse.jst.web_ui.feature.feature.group
    # WST Web Standard Tools
    - org.eclipse.wst.web_ui.feature.feature.group
    - org.eclipse.wst.xml_ui.feature.feature.group
    - org.eclipse.wst.common.fproj.feature.group
    - org.eclipse.wst.server_adapters.feature.feature.group

  # Maven
  - repository: "{{ eclipse_release_repo }}"
    units:
    - org.eclipse.m2e.feature.feature.group
    - org.eclipse.m2e.wtp.jaxrs.feature.feature.group
    - org.eclipse.m2e.wtp.jpa.feature.feature.group
    - org.eclipse.m2e.wtp.jsf.feature.feature.group
    - org.eclipse.m2e.wtp.feature.feature.group
    - org.sonatype.m2e.mavenarchiver.feature.feature.group

  # m2e Tycho Configurator
  - repository: "http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST/"
    units:
    - org.sonatype.tycho.m2e.feature.feature.group

  # Mylyn
  - repository: "{{ eclipse_release_repo }}"
    units:
    - org.eclipse.mylyn.git.feature.group
    - org.eclipse.mylyn.github.feature.feature.group

  command: >
           {{ eclipse_localdir | mandatory }}/eclipse/eclipse
           -clean -purgeHistory
           -application org.eclipse.equinox.p2.director -noSplash
           -repository {{ item.repository | mandatory }}
           -destination "{{ eclipse_localdir }}/eclipse"
           -profileProperties org.eclipse.update.install.features=true
           -installIU {{ item.units | mandatory | join(',') }}
  ignore_errors: yes
