---
# file: roles/eclipse/tasks/main.yml

- name: Prepare Eclipse download script
  template: src=eclipse_download.j2
            dest={{ eclipse_localdir }}/eclipse_download.sh
            mode=0555

- name: Download Eclipse
  command: creates="{{ eclipse_localdir }}/{{ eclipse_archive }}"
           "{{ eclipse_localdir }}/eclipse_download.sh"

- name: Extract Eclipse
  command: chdir="{{ eclipse_localdir }}" creates="eclipse"
           tar -xvf "{{ eclipse_archive }}"

- name: Eclipse directory owner and group
  file: state=directory path="{{ eclipse_localdir }}/eclipse"
        recurse=yes owner={{ eclipse_owner }} group={{ eclipse_owner }}

- name: Create Eclipse desktop launcher icon
  template: src=eclipse.desktop.j2
            dest=~{{ eclipse_owner }}/.local/share/applications/eclipse.desktop
            owner={{ eclipse_owner }} group={{ eclipse_owner }}

- name: Eclipse feature groups
  with_items: eclipse_feature_groups | default([])
  command: >
           {{ eclipse_localdir | mandatory }}/eclipse/eclipse
           -clean -purgeHistory
           -application org.eclipse.equinox.p2.director -noSplash
           -repository {{ item.repository | mandatory }}
           -destination "{{ eclipse_localdir }}/eclipse"
           -profileProperties org.eclipse.update.install.features=true
           -installIU {{ item.units | mandatory | join(',') }}
  ignore_errors: yes
