# file: roles/developer_profile/tasks/main.yml

- name: Developer user account
  user: name={{ profile_username }} comment="{{ profile_fullname }}" append=yes groups=wheel shell=/bin/bash generate_ssh_key=yes ssh_key_comment={{ profile_username }}@{{ ansible_fqdn }}-{{ ansible_date_time.iso8601 }} state=present

- name: Git configuration
  template: src=gitconfig.j2 dest=/home/{{ profile_username }}/.gitconfig owner={{ profile_username }} group={{ profile_username }} mode=0664 force=no

- name: Maven settings directory
  file: path=/home/{{ profile_username }}/.m2 state=directory owner={{ profile_username }} group={{ profile_username }}

- name: Maven settings
  template: src=settings.xml.j2 dest=/home/{{ profile_username }}/.m2/settings.xml owner={{ profile_username }} group={{ profile_username }} mode=0660 force=no backup=yes
