# file: dropbox_headless.yaml
#
# Dropbox Headless install for the ansible_user
#
# When you first install Dropbox Headless as a service
# you will find a message like this in the service log:
#
#     This computer isn't linked to any Dropbox account...
#     Please visit https://www.dropbox.com/cli_link_nonce?nonce=abcdef0123456789abcdef0123456789 to link this device.
#
# Follow the instructions to link it.
#
# Check the service status like so:
#
#     systemctl --user status dropbox
#
# You can view the service log for example like so:
#
#     journalctl --user-unit=dropbox --since "15m ago" --output=short-iso --no-hostname --no-pager
#
---

- hosts: localhost
  connection: local
  roles:
  - dropbox
