# file: roles/local_users/tasks/main.yaml
---

- name: Local user accounts
  with_items: "{{ local_users | default([]) }}"
  user:
    name: "{{ item.user }}"
    comment: "{{ item.fullname }}"
    append: yes
    groups: "{{ item.groups | default('') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    generate_ssh_key: yes
    ssh_key_bits: "{{ ssh_key_bits | default(4096) }}"
    ssh_key_type: "{{ ssh_key_type | default('rsa') }}"
    ssh_key_comment: "{{ item.user }}@{{ ansible_fqdn }}_{{ ansible_date_time.iso8601 | replace(':', '') }}"
    state: "{{ item.state | default('present') }}"

- name: Git configuration
  with_items: "{{ local_users | default([]) }}"
  template:
    src: gitconfig.j2
    dest: "/home/{{ item.user }}/.gitconfig"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0664
    force: no

- name: Maven settings directory
  with_items: "{{ local_users | default([]) }}"
  file:
    path: "/home/{{ item.user }}/.m2"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"

- name: Maven settings
  with_items: "{{ local_users | default([]) }}"
  template:
    src: settings.xml.j2
    dest: "/home/{{ item.user }}/.m2/settings.xml"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0660
    force: no
    backup: yes

- name: Scripts in /usr/local/bin/
  with_items:
  - "git-pull-workspace"
  copy:
    src: "{{ item }}.sh"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0775
    force: yes
