# file: roles/fedora_virtualization/tasks/main.yml
---

- name: Virtualization packages
  with_items:
  - "@Virtualization"
  - libvirt
  - libguestfs-tools
  - avahi-dnsconfd
  become: yes
  dnf: name="{{ item }}" state=present

- name: Verify Linux KVM kernel modules
  become: yes
  shell: lsmod | grep kvm
  register: kernel_modules
  changed_when: False
  failed_when: not 'kvm' in kernel_modules.stdout

- name: Allow libvirt management access
  become: yes
  template: src=libvirt-policy.conf.j2
            dest="/etc/polkit-1/localauthority.conf.d/50-libvirt-policy.conf"
            owner=root group=root mode=0644

- name: Enable services
  with_items:
  - dbus
  - avahi-daemon
  - libvirtd
  become: yes
  service: name="{{ item }}" state=started enabled=yes
