# file: roles/java_oracle/tasks/main.yml

- name: Prepare Oracle Java download script
  sudo: yes
  template: src=oracle_download.j2 dest={{ java_oracle_localdir | mandatory }}/oracle_download.sh mode=0555

- name: Download Oracle Java
  sudo: yes
  command: "{{ java_oracle_localdir }}/oracle_download.sh creates={{ java_oracle_localdir }}/{{ java_oracle_archive | mandatory }}"
  register: java_oracle_downloaded

- name: Install the Oracle Java RPM
  sudo: yes
  command: chdir={{ java_oracle_localdir }} rpm -U {{ java_oracle_archive }} creates="{{ java_oracle_home | mandatory }}"
  register: java_oracle_installed

- name: Set Oracle java as default
  sudo: yes
  command: alternatives --set java "{{ java_oracle_home }}/bin/java"
  when: java_oracle_installed.changed and ansible_distribution == 'Fedora'

- name: Set Oracle jar as default
  sudo: yes
  command: alternatives --set jar "{{ java_oracle_home }}/bin/jar"
  when: java_oracle_installed.changed and ansible_distribution == 'Fedora'
