- name: ensure workspace exists
  file: path="{{ pro_workspace }}" state=directory

- name: git checkout projects
  git: force=no repo="{{ pro_repos }}/{{ item }}.git" dest="{{ pro_workspace }}/{{ item }}"
  with_items: pro_modules
