# file: roles/common/tasks/main.yaml
---

- name: Common packages (dnf)
  when: ansible_pkg_mgr == "dnf"
  with_items: "{{ common_packages }}"
  dnf:
    name: "{{ item }}"

- name: Common packages (yum)
  when: ansible_pkg_mgr == "yum"
  with_items: "{{ common_packages }}"
  yum:
    name: "{{ item }}"
