# file: roles/common/tasks/main.yml
---

- name: Common packages
  with_items:
  - firewalld
  - gdb
  - git
  - gnupg
  - htop
  - jwhois
  - lftp
  - libselinux-python
  - lookup
  - lv
  - man
  - maven
  - midori
  - nano
  - postgresql
  - pv
  - python-boto
  - rkhunter
  - screen
  - wget
  dnf: name={{ item }}
